apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-staging-domain
spec:
  secretName: cert-wildcard-staging-domain
  issuerRef:
    name: le-staging-wildcard-issuer
    kind: ClusterIssuer
  commonName: "*.k8s.etimo.se"
  dnsNames:
    - "*.k8s.etimo.se"
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-staging-wildcard-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: daniel.winther@etimo.se
    privateKeySecretRef:
      name: le-staging-wildcard-issuer
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-dns
              key: access-token
