# Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: provisioned-config
  namespace: "achievements-live"
  labels:
    provisioner: etimo-kubernetes
data:
  DB_MAIN_NAME: "achievements_live_staging_main"
  DB_MAIN_USER: "achievements_live_staging_main"
  DB_MAIN_PORT: "25060"
  DB_MAIN_PUBLIC_HOST: "staging-shared-do-user-11119612-0.b.db.ondigitalocean.com"
  DB_MAIN_PRIVATE_HOST: "private-staging-shared-do-user-11119612-0.b.db.ondigitalocean.com"
  DB_MAIN_CA: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVRVENDQXFtZ0F3SUJBZ0lVSXNGL3hrRkM2am9XUVhiaGNkUXlMSFNNV3R3d0RRWUpLb1pJaHZjTkFRRU0KQlFBd09qRTRNRFlHQTFVRUF3d3ZOMk0zWVRZMk1XRXRaVFl6TlMwMFlqQm1MVGc1TjJRdE56VXpZbUkyTmpWaQpabUl3SUZCeWIycGxZM1FnUTBFd0hoY05Nakl3TXpJMU1qTXdOelV6V2hjTk16SXdNekl5TWpNd056VXpXakE2Ck1UZ3dOZ1lEVlFRRERDODNZemRoTmpZeFlTMWxOak0xTFRSaU1HWXRPRGszWkMwM05UTmlZalkyTldKbVlqQWcKVUhKdmFtVmpkQ0JEUVRDQ0FhSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnR1BBRENDQVlvQ2dnR0JBTHNSd2RkYQpQaUJkVi9xYi9OaWVCTFZlMTdGdXJwZ3VYeHpuSVN3SEdPRHl3MzJ4bStod1hucCttUkVZRWFydFlxYkFHbVY4CmZnbmxYb1N3YzV1MUNDZElCNXVYVnJlbmF0K0s3Q0NSS3dOYnRsb3VIamhOVzlsWGJFY1JsVStYdVFlRFhjQWsKbFZiR2t1TmozMnJmOTBGYTA2dTRrV2h6UEdHYlZsTkEzRGlTd2hEbW1QV2JtUGVmOUpIczFZWWhMemQrYlZzTgpUVHN4VjBuSnI3Zk5XcFZIc01kc2NTcVYyMFhuQitNNG9GTnVBanZ2bVJjNzM5NXZYcDVrOU10NjhHUThMd05PCmEyWkd5Z1UwbDhMV2NjQkxOTFd1UkZwLzRYMUcrbnZmQ1kxYXBFSFpHbkhIdkZTOTBtMXVRbFpzc05QZXl1RHEKazRwYXRTNUxhL3IwYzlXcytqT09ZYjZabXhyaEdUTjBXYWZCVXBlZkdFTGorNW9aZkxRUTZGYlVMdGJNbFZENwpkSHkrbkFDdWlKalJQelFieXNXUU9qU3VnQlh0YndmYkRJVlpoZ2Vndmt2N0ZYQTVUclAzdHpESjh4eExWbTFWCjUyYUtLeFhXMTdibFFUb0RUcHlybHAySy81ZDZQMlVSdUlINys2djBKSjN4ODh1YVZwZlpWNWlOZ1FJREFRQUIKb3o4d1BUQWRCZ05WSFE0RUZnUVVpNjVGbWhnQm5BcHREMEFXUVFQVU0zVmd1SEF3RHdZRFZSMFRCQWd3QmdFQgovd0lCQURBTEJnTlZIUThFQkFNQ0FRWXdEUVlKS29aSWh2Y05BUUVNQlFBRGdnR0JBRGJuVCt1K1JkcXhVUjRMCmRHSGtHMzB4UiswSElMRm03VVdFZXRJN25yays1c1R3RDhSOXJmek14cGR2dXpzMGdxYWc2YjBIalhmRE11dHIKeVBGUGZkdllxSmFxZ3IvRFRDcTB6SndsM2I5ZTN4dE9sZ1NvdUJPRWQzdmRlTysyY1VnRkNjL3V4Nk5mTldOagpnU2tTZXh2bzI5cWpnWUY1UzZOUjZjdktzQVVFdkFhY2UyRGxnZzcxT2lsQWNtRDRTaFVwTFJPbkU3YVlHZEt6ClBKRXhnbllsUlg5Y2ZzNFB3SlRLR05EWk81UlVHeGtVQ3pUVUw4aGN6NVVhWE1jaG9mTVM3ODlHd1pHMzhna3EKaTZTZ3pVV0JCVFFpb0VSVFRFdnJzV1loT0FkemZoeFBZQjRzSmdXaWc1S29od2hlVGw3MURLMkhRSDBaOCt6YQp6SVhPNHZDK0ZGVS9KcGYwU2hNbWEyUFdLT001NmRaTjg3cno4eHRFcTY3RmNIbUxaZW1hc0lUbjNLVkdsTmxhClMxY3JrdHFGM3hWWmM1WWdMOWorMFMvRzVkS3lCUnVtVjlXbkt5b0VKU2NaRXVqM2FmNFFjREdVOTladUQ2blkKWUNoNmE0U3A2RmJJajBOWW1FWHRsMVBraWRrNmZBaTI1eVdVcWNtYnRJZmUzTXZ5a1E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg&#x3D;&#x3D;"
---
# We apply a resource quota to all namespaces to prevent starvation from other projects
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu
  namespace: "achievements-live"
  labels:
    provisioner: etimo-kubernetes
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 1.5Gi
---
# Admin role for the project which gives full access to the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "achievements-live"
  name: "achievements-live-admin"
rules:
  - apiGroups: ["", "extensions", "apps", "networking.k8s.io", "batch"]
    resources: ["*"]
    verbs: ["*"]
---
# Bind the admin role to all users in this project
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "achievements-live-admins"
  namespace: "achievements-live"
roleRef:
  kind: Role
  name: "achievements-live-admin"
  apiGroup: ""
subjects:
  - kind: User
    name: "niclaslindstedt"
    apiGroup: ""
