apiVersion: v1
kind: Namespace
metadata:
  name: "etimo-achievements"
  labels:
    provisioner: etimo-kubernetes
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu
  namespace: "etimo-achievements"
  labels:
    provisioner: etimo-kubernetes
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 0.5Gi
    limits.cpu: "1"
    limits.memory: 1Gi
