apiVersion: v1
kind: Namespace
metadata:
  name: "test"
  labels:
    provisioner: etimo-kubernetes
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu
  namespace: "test"
  labels:
    provisioner: etimo-kubernetes
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 0.5Gi
    limits.cpu: "1"
    limits.memory: 1Gi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "test"
  name: "test-ro"
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "test-ro"
  namespace: "test"
roleRef:
  kind: Role
  name: "test-ro"
  apiGroup: ""
subjects:
  - kind: User
    name: "indrif"
    apiGroup: ""
