# Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: provisioned-config
  namespace: "test-mogge"
  labels:
    provisioner: etimo-kubernetes
data:
---
# We apply a resource quota to all namespaces to prevent starvation from other projects
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu
  namespace: "test-mogge"
  labels:
    provisioner: etimo-kubernetes
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 1.5Gi
---
# Admin role for the project which gives full access to the namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: "test-mogge"
  name: "test-mogge-admin"
rules:
  - apiGroups: ["", "extensions", "apps", "networking.k8s.io", "batch"]
    resources: ["*"]
    verbs: ["*"]
---
# Bind the admin role to all users in this project
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "test-mogge-admins"
  namespace: "test-mogge"
roleRef:
  kind: Role
  name: "test-mogge-admin"
  apiGroup: ""
subjects:
  - kind: User
    name: "morgan-cromell"
    apiGroup: ""
