apiVersion: v1
kind: ConfigMap
metadata:
  name: migrations
  namespace: default
  labels:
    provisioner: etimo-kubernetes
data:
  applied: |
    {"kubernetes/migrations/0001_helm.js":{"checksum":"b7339c01f46abd57387ced627c9b422c42a68d03","ts":"2022-03-22T07:21:10.446Z"},"kubernetes/migrations/0002_test.js":{"checksum":"b9274f5fb83a8fbcbbe9634a7b053e286d3f156b","ts":"2022-03-22T07:21:10.778Z"}}
---
