apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "etimo-kubernetes-ro"
roleRef:
  kind: ClusterRole
  name: "view"
  apiGroup: "rbac.authorization.k8s.io"
subjects:
- kind: User
  name: "indrif"
  apiGroup: ""
- kind: User
  name: "niclaslindstedt"
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "etimo-kubernetes-metrics-reader"
roleRef:
  kind: ClusterRole
  name: "system:aggregated-metrics-reader"
  apiGroup: "metrics.k8s.io"
subjects:
- kind: User
  name: "indrif"
  apiGroup: ""
- kind: User
  name: "niclaslindstedt"
  apiGroup: ""

