apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu
  labels:
    provisioner: etimo-kubernetes
spec:
  hard:
    requests.cpu: "0.5"
    requests.memory: 1Gi
    limits.cpu: "1"
    limits.memory: 2Gi
