name: Check syntax
on:
  pull_request:
  push:
    branches-ignore:
      - main
    paths:
      - "projects/"
jobs:
  check-syntax:
    timeout-minutes: 10
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - run: yarn
      - run: yarn validate
