name: Provision
on:
  push:
    branches:
      - main
concurrency: provision-${{ github.ref }}
jobs:
  provision:
    timeout-minutes: 10
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - run: yarn
      - run: yarn render:codeowners --dry-run
      - run: yarn render:terraform --dry-run
      - run: yarn render:codeowners
      - run: yarn render:terraform
      - run: git diff

      # - name: Setup Terraform
      #   uses: hashicorp/setup-terraform@v1
      #   with:
      #     cli_config_credentials_token: ${{ secrets.TERRAFORM_API_TOKEN }}

      # - name: Terraform Format
      #   id: fmt
      #   working-directory: terraform
      #   run: terraform fmt -check

      # - name: Terraform Init
      #   id: init
      #   working-directory: terraform
      #   run: terraform init

      # - name: Terraform Validate
      #   id: validate
      #   working-directory: terraform
      #   run: terraform validate -no-color

      # - name: Install doctl
      #   uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      # - name: Save DigitalOcean kubeconfig with short-lived credentials
      #   run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 staging-cluster

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Github Actions job result2
          to: daniel.winther@etimo.se
          from: Daniel Winther <daniel.winther@etimo.se>
          secure: true
          body: Välkommen till Etimo Kubernetes!
          html_body: Hello world # file://README.html
          ignore_cert: true
          convert_markdown: true
          attachments: ./package.json
